name: pulumi-test
runtime:
    name: nodejs
    options:
        packagemanager: npm
description: For Testing an IaC with Azure
config:
    pulumi:tags:
        value:
            pulumi:template: azure-typescript
